### ISSUE TITLE
TypeError: transformTagsMap[name] is not a function

### ISSUE THREAD

**Issue by buglloc** [punkave/sanitize-html#101]
Test code:
```js
var sanitizeHtml = require('sanitize-html');
var clean = sanitizeHtml('!<__proto__>!');

console.log(clean);
```

Current result:
```
/home/buglloc/tmp/sanit/node_modules/sanitize-html/index.js:118
        transformedTag = transformTagsMap[name](name, attribs);
                                               ^

TypeError: transformTagsMap[name] is not a function
    at Object.htmlparser.Parser.onopentag (/home/buglloc/tmp/sanit/node_modules/sanitize-html/index.js:118:48)
    at Parser.onopentagend (/home/buglloc/tmp/sanit/node_modules/htmlparser2/lib/Parser.js:171:37)
    at Tokenizer._stateBeforeAttributeName (/home/buglloc/tmp/sanit/node_modules/htmlparser2/lib/Tokenizer.js:230:13)
    at Tokenizer._parse (/home/buglloc/tmp/sanit/node_modules/htmlparser2/lib/Tokenizer.js:658:9)
    at Tokenizer.write (/home/buglloc/tmp/sanit/node_modules/htmlparser2/lib/Tokenizer.js:632:7)
    at Parser.write (/home/buglloc/tmp/sanit/node_modules/htmlparser2/lib/Parser.js:333:18)
    at sanitizeHtml (/home/buglloc/tmp/sanit/node_modules/sanitize-html/index.js:262:10)
    at Object.<anonymous> (/home/buglloc/tmp/sanit/2.js:2:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

```

Expected result:
```
!!
```

**Comment by boutell** [comment]
Just pushed a fix in 9aad900209a62b5c2607b70779ff90d0c67f0648 thanks

I published these fixes to npm.
